services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=song_library_user
      - DB_PASSWORD=song_library_password
      - DB_NAME=song_library_db
    networks:
      - song-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=song_library_user
      - POSTGRES_PASSWORD=song_library_password
      - POSTGRES_DB=song_library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - song-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - song-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  song-network:
    driver: bridge
