// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

//nolint:unused
import _ "github.com/swaggo/swag"

// @title           Song Library API
// @version         1.0
// @description     API для управления библиотекой песен
// @host           localhost:8080
// @BasePath       /api/v1
// @schemes        http
